/**
 * This class is generated by jOOQ
 */
package synitex.backup.db.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import synitex.backup.db.tables.BackupHistory;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BackupHistoryRecord extends UpdatableRecordImpl<BackupHistoryRecord> implements Record9<Long, String, String, Long, Long, Integer, Long, Long, Long> {

	private static final long serialVersionUID = 1176521196;

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.DESTINATION_ID</code>.
	 */
	public void setDestinationId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.DESTINATION_ID</code>.
	 */
	public String getDestinationId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.SOURCE_ID</code>.
	 */
	public void setSourceId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.SOURCE_ID</code>.
	 */
	public String getSourceId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.STARTED_AT</code>.
	 */
	public void setStartedAt(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.STARTED_AT</code>.
	 */
	public Long getStartedAt() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.FINISHED_AT</code>.
	 */
	public void setFinishedAt(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.FINISHED_AT</code>.
	 */
	public Long getFinishedAt() {
		return (Long) getValue(4);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.EXIT_CODE</code>.
	 */
	public void setExitCode(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.EXIT_CODE</code>.
	 */
	public Integer getExitCode() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.TRANSFERED_FILES_SIZE</code>.
	 */
	public void setTransferedFilesSize(Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.TRANSFERED_FILES_SIZE</code>.
	 */
	public Long getTransferedFilesSize() {
		return (Long) getValue(6);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.FILES_SIZE</code>.
	 */
	public void setFilesSize(Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.FILES_SIZE</code>.
	 */
	public Long getFilesSize() {
		return (Long) getValue(7);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.TOTAL_TRANSFERED_SIZE</code>.
	 */
	public void setTotalTransferedSize(Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.TOTAL_TRANSFERED_SIZE</code>.
	 */
	public Long getTotalTransferedSize() {
		return (Long) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Long, String, String, Long, Long, Integer, Long, Long, Long> fieldsRow() {
		return (Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row9<Long, String, String, Long, Long, Integer, Long, Long, Long> valuesRow() {
		return (Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return BackupHistory.BACKUP_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return BackupHistory.BACKUP_HISTORY.DESTINATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return BackupHistory.BACKUP_HISTORY.SOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return BackupHistory.BACKUP_HISTORY.STARTED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return BackupHistory.BACKUP_HISTORY.FINISHED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return BackupHistory.BACKUP_HISTORY.EXIT_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field7() {
		return BackupHistory.BACKUP_HISTORY.TRANSFERED_FILES_SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field8() {
		return BackupHistory.BACKUP_HISTORY.FILES_SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field9() {
		return BackupHistory.BACKUP_HISTORY.TOTAL_TRANSFERED_SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDestinationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getStartedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getFinishedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getExitCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value7() {
		return getTransferedFilesSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value8() {
		return getFilesSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value9() {
		return getTotalTransferedSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value2(String value) {
		setDestinationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value3(String value) {
		setSourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value4(Long value) {
		setStartedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value5(Long value) {
		setFinishedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value6(Integer value) {
		setExitCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value7(Long value) {
		setTransferedFilesSize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value8(Long value) {
		setFilesSize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value9(Long value) {
		setTotalTransferedSize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord values(Long value1, String value2, String value3, Long value4, Long value5, Integer value6, Long value7, Long value8, Long value9) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BackupHistoryRecord
	 */
	public BackupHistoryRecord() {
		super(BackupHistory.BACKUP_HISTORY);
	}

	/**
	 * Create a detached, initialised BackupHistoryRecord
	 */
	public BackupHistoryRecord(Long id, String destinationId, String sourceId, Long startedAt, Long finishedAt, Integer exitCode, Long transferedFilesSize, Long filesSize, Long totalTransferedSize) {
		super(BackupHistory.BACKUP_HISTORY);

		setValue(0, id);
		setValue(1, destinationId);
		setValue(2, sourceId);
		setValue(3, startedAt);
		setValue(4, finishedAt);
		setValue(5, exitCode);
		setValue(6, transferedFilesSize);
		setValue(7, filesSize);
		setValue(8, totalTransferedSize);
	}
}
