/**
 * This class is generated by jOOQ
 */
package synitex.backup.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import synitex.backup.db.tables.BackupHistory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BackupHistoryRecord extends UpdatableRecordImpl<BackupHistoryRecord> implements Record6<Long, String, String, Long, Long, Integer> {

	private static final long serialVersionUID = 169660466;

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.ID</code>.
	 */
	public void setId(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.ID</code>.
	 */
	public Long getId() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.DESTINATION_ID</code>.
	 */
	public void setDestinationId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.DESTINATION_ID</code>.
	 */
	public String getDestinationId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.SOURCE_ID</code>.
	 */
	public void setSourceId(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.SOURCE_ID</code>.
	 */
	public String getSourceId() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.STARTEDAT</code>.
	 */
	public void setStartedat(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.STARTEDAT</code>.
	 */
	public Long getStartedat() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.ENDEDAT</code>.
	 */
	public void setEndedat(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.ENDEDAT</code>.
	 */
	public Long getEndedat() {
		return (Long) getValue(4);
	}

	/**
	 * Setter for <code>BACKUP.BACKUP_HISTORY.EXITCODE</code>.
	 */
	public void setExitcode(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>BACKUP.BACKUP_HISTORY.EXITCODE</code>.
	 */
	public Integer getExitcode() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, String, Long, Long, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, String, String, Long, Long, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return BackupHistory.BACKUP_HISTORY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return BackupHistory.BACKUP_HISTORY.DESTINATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return BackupHistory.BACKUP_HISTORY.SOURCE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return BackupHistory.BACKUP_HISTORY.STARTEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return BackupHistory.BACKUP_HISTORY.ENDEDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return BackupHistory.BACKUP_HISTORY.EXITCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDestinationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getSourceId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getStartedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getEndedat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getExitcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value1(Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value2(String value) {
		setDestinationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value3(String value) {
		setSourceId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value4(Long value) {
		setStartedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value5(Long value) {
		setEndedat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord value6(Integer value) {
		setExitcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BackupHistoryRecord values(Long value1, String value2, String value3, Long value4, Long value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BackupHistoryRecord
	 */
	public BackupHistoryRecord() {
		super(BackupHistory.BACKUP_HISTORY);
	}

	/**
	 * Create a detached, initialised BackupHistoryRecord
	 */
	public BackupHistoryRecord(Long id, String destinationId, String sourceId, Long startedat, Long endedat, Integer exitcode) {
		super(BackupHistory.BACKUP_HISTORY);

		setValue(0, id);
		setValue(1, destinationId);
		setValue(2, sourceId);
		setValue(3, startedat);
		setValue(4, endedat);
		setValue(5, exitcode);
	}
}
