image:https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/ssinica/backup?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

# Backup

WARNING: Being too busy to worry about backup is like being too busy driving a car to put on a seatbelt.

## Terminology ##

bc-destination:: The location where the files are copied. Can be: `SSH`, `LOCAL`, `S3`, etc...
bc-node:: Utility which resides on client computer. `bc-node` backups data to `bc-destination`.
bc-master:: Host which monitors all `bc-nodes`. Provides an admin interface to review backup solution in general.

## TOC ##

* link:docs/mount-usb-drive.adoc[How to mount USB drive (Debian)]
* link:docs/setup-ssh-bc-destination.adoc[How to setup SSH bc-destination]
* link:docs/releasing-guide.adoc[How to release]

## How to build ##

* Ensure `JAVA_HOME` env variable points to JDK8
* See `x-build.cmd` as an example build script. Essentially that it does is simple:
+
----
mvn clean install
----

## How to run bc-node from IDE ##

* Main class: `synitex.backup.Application`
* VM options:
** `-Djava.awt.headless=false`, for GUI mode
** `-Djava.awt.headless=true`, for CLI mode
* Program arguments: `--spring.profiles.active=dev`. To load configuration file from `./bc-node/config/application-dev.yml`.
+
You can copy example configuration file `./bc-distro/config/application-example.yml` to `./bc-node/config/application-dev.yml`.
* Working directory: `{project.path}\bc-node`

## bc-node configuration ##

See link:bc-distro/config/application-example.yml[application-example.yml] for configuration options.

The main idea:

* Each `bc-node` has uniq `Application Id`. This ID is used in folder layout on bc-destinations. Also in future this ID might be used in bc-master to identify backup clients.
* Configuration contains a list of bc-destinations. Currently `SSH` and `LOCAL` destinations are supported.
* Configuration contains a list of backup items. For each backup item you should specify `Destination ID` and link:http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/support/CronSequenceGenerator.html[CRON] expression.

