app:
  id: ssinica-dev

rsync:
  cmd: rsync

destination:
  items:
    - id: pi.sinica.me
      name: pi.sinica.me
      type: SSH
      key: c:/users/PC/.ssh/pi.sinica.me__bc
      user: bc
      host: pi
      dir: /data/backup
      partialDir: /data/backup/partial
    - id: hdd.sergey
      name: Sergey's noute external HDD
      type: LOCAL
      dir: /cygdrive/d/backup

backup:
  items:
    - name: Books 2 Go (PI)
      source: /cygdrive/c/my/books2go
      destination: pi.sinica.me
      schedule: '0 * * * * *'
      timeout: 3600
    - name: Books 2 Go (HDD)
      source: /cygdrive/c/my/books2go
      destination: hdd.sergey
      schedule: '30 * * * * *'
