server:
  port: 9999

rsync:
  cmd: rsync

xmpp:
  enabled: false

spring:
  datasource:
    url: ${db.url}
    username: ${db.user}
    password:
    driver-class-name: org.hsqldb.jdbcDriver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5