app:
  id: [Application Id]

rsync:
  cmd: [Path to rsync executable. Default value = rsync]

server:
  port: [Server port. Default value = 9999]

spring:
  datasource:
    url: [Default value = jdbc:hsqldb:file:~/bc-node/data/backupdb]

xmpp:
  enabled: [XMPP notifications are enabled? Default value = false]
  domain: [XMPP server domain. Example = jabber.ru]
  sender: [XMPP user name]
  senderPass: [XMPP user password]
  receiver: [XMPP user name to send notification to. Can be the same as 'sender']

notification:
  backupFailed: [Send notification if backup failed? Default value = false]
  backupSuccess: [Send notification if backup success? Default value = false]

backup:
  destinations:
    - id: [Destination Id]
      name: [Human readable name of destination]
      dir: [Path to backup directory on bc-destination]
      type: [one of = SSH, LOCAL]
      key: [Path to private key file used to connect to SSH bc-destination]
      user: [User used to connect to SSH bc-destination]
      host: [Host used to connect to SSH bc-destination]
      partialDir: [Optional path to partial uploads on bc-destination. Mostly useful for SSH bc-destinations]
  sources:
    - id: [ID of backup item]
      path: [Directory to backup]
      destination: [Destination Id]
  tasks:
    - source: [Source ID]
      destination: [Destination ID]
      schedule: [Single quoted CRON expression]
      timeout: [Rsync timeout. Default value (sec) = 600]
      heartbeat: [How othen to check backup. Default value (min) = 10]
