/**
 * This class is generated by jOOQ
 */
package synitex.backup.db;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import synitex.backup.db.tables.BackupHistory;
import synitex.backup.db.tables.records.BackupHistoryRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>BACKUP</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<BackupHistoryRecord, Long> IDENTITY_BACKUP_HISTORY = Identities0.IDENTITY_BACKUP_HISTORY;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<BackupHistoryRecord> SYS_PK_10113 = UniqueKeys0.SYS_PK_10113;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<BackupHistoryRecord, Long> IDENTITY_BACKUP_HISTORY = createIdentity(BackupHistory.BACKUP_HISTORY, BackupHistory.BACKUP_HISTORY.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<BackupHistoryRecord> SYS_PK_10113 = createUniqueKey(BackupHistory.BACKUP_HISTORY, BackupHistory.BACKUP_HISTORY.ID);
	}
}
