/**
 * This class is generated by jOOQ
 */
package synitex.backup.db;


import javax.annotation.Generated;

import synitex.backup.db.tables.BackupHistory;
import synitex.backup.db.tables.SizeHistory;


/**
 * Convenience access to all tables in BACKUP
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table BACKUP.BACKUP_HISTORY
	 */
	public static final BackupHistory BACKUP_HISTORY = synitex.backup.db.tables.BackupHistory.BACKUP_HISTORY;

	/**
	 * The table BACKUP.SIZE_HISTORY
	 */
	public static final SizeHistory SIZE_HISTORY = synitex.backup.db.tables.SizeHistory.SIZE_HISTORY;
}
